spring:
  cloud:
    gateway:
      routes:
      - id: HOTEL-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/hotels/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**
       
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**